### ISSUE TITLE
Installation fails on Ubuntu 12.04 64

### ISSUE THREAD

**Issue by timlinux** [kandanapp/kandan#276]
# Problem

Installation on a freshly installed ubuntu 12.04 virtual machine fails with:

``` bash
[test@192.168.1.116] run: bundle exec rake db:create db:migrate kandan:bootstrap
[test@192.168.1.116] out: /usr/lib/ruby/vendor_ruby/bundler/rubygems_ext.rb:8:in `require': no such file to load -- rubygems (LoadError)
[test@192.168.1.116] out:   from /usr/lib/ruby/vendor_ruby/bundler/rubygems_ext.rb:8
[test@192.168.1.116] out:   from /usr/lib/ruby/vendor_ruby/bundler.rb:11:in `require'
[test@192.168.1.116] out:   from /usr/lib/ruby/vendor_ruby/bundler.rb:11
[test@192.168.1.116] out:   from /usr/bin/bundle:4:in `require'
[test@192.168.1.116] out:   from /usr/bin/bundle:4
[test@192.168.1.116] out: 
```
# Notes

I am deploying using a fabric script (hence the slightly different looking shell output above, but otherwise the target host is a stock Ubuntu Desktop 12.04 64 bit installation with not other software installed.
# Expected outcome

When following the installation guide (in particular https://github.com/kandanapp/kandan/blob/master/DEPLOY.md#stand-alone-server) it would be great if the installation would work on this popular LTS version of ubuntu 'out of the box'.

**Comment by fusion94** [comment]
Closing as part of the Kandan revival. The app is being rebuilt from scratch at DamageLabs/kandan-core on a modern stack (Angular 21 + Express/Socket.io). See https://github.com/DamageLabs/kandan-core for the new version.
