### ISSUE TITLE
Trying to deploy kandan over cloud foundry

### ISSUE THREAD

**Issue by narendrachoudhary** [kandanapp/kandan#426]
Hi ,

I am trying to deploy chat application on cloud foundry version 170 and there i am getting the below error :...

Using manifest file /home/rahul/kandan/manifest.yml

Updating app chat in org demo / space demo as demo...
OK

Uploading chat...
Uploading app files from: /home/rahul/kandan
Uploading 17.6M, 7917 files
Done uploading               
OK

Stopping app chat in org demo / space demo as demo...
OK

Starting app chat in org demo / space demo as demo...
-----> Downloaded app package (19M)
Cloning into '/tmp/buildpacks/heroku-buildpack-ruby'...
-----> Compiling Ruby/Rails

FAILED
Server error, status code: 400, error code: 170001, message: Staging error: cannot get instances since staging failed

TIP: use 'cf logs chat --recent' for more information
root@bosh-clir2:/home/rahul/kandan# cf logs chat --recent 
Connected, dumping recent logs for app chat in org demo / space demo as demo...

2015-01-28T06:51:46.18+0000 [API]     ERR Encountered error: Staging error: failed to stage application:
2015-01-28T06:51:46.18+0000 [API]     ERR Script exited with status 1
2015-01-28T06:51:51.37+0000 [STG]     ERR /var/vcap/packages/dea_next/buildpacks/lib/installer.rb:19:in `compile': Buildpack compilation step failed: (RuntimeError)
2015-01-28T06:51:51.37+0000 [STG]     ERR 	from /var/vcap/packages/dea_next/buildpacks/lib/buildpack.rb:74:in `block in compile_with_timeout'
2015-01-28T06:51:51.37+0000 [STG]     ERR 	from /usr/lib/ruby/1.9.1/timeout.rb:68:in `timeout'
2015-01-28T06:51:51.37+0000 [STG]     ERR 	from /var/vcap/packages/dea_next/buildpacks/lib/buildpack.rb:73:in `compile_with_timeout'
2015-01-28T06:51:51.37+0000 [STG]     ERR 	from /var/vcap/packages/dea_next/buildpacks/lib/buildpack.rb:54:in `block in stage_application'
2015-01-28T06:51:51.37+0000 [STG]     ERR 	from /var/vcap/packages/dea_next/buildpacks/lib/buildpack.rb:50:in `chdir'
2015-01-28T06:51:51.37+0000 [STG]     ERR 	from /var/vcap/packages/dea_next/buildpacks/lib/buildpack.rb:50:in `stage_application'
2015-01-28T06:51:51.37+0000 [STG]     ERR 	from /var/vcap/packages/dea_next/buildpacks/bin/run:10:in `<main>'

**Comment by narendrachoudhary** [comment]
Could anyone suggest me what should i check to resolve the same.

**Comment by fusion94** [comment]
Closing as part of Kandan revival project. The app is being rebuilt from scratch on a modern stack (Angular + Express/Node). See the upcoming kandan-core repository for the new version.
